// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AnalyzeBidsResponse
 */
export type AnalyzeBidsResponse = {
    /**
     * Results
     */
    results: Array<BidMatchResult>;
};

/**
 * BidFitRequest
 */
export type BidFitRequest = {
    /**
     * Bid Source
     */
    bid_source?: string | null;
    /**
     * Bid Content
     */
    bid_content?: string | null;
    /**
     * Bid Loader
     */
    bid_loader: string;
    /**
     * Bid Chunker
     */
    bid_chunker?: string;
    /**
     * Top K
     */
    top_k?: number;
    /**
     * Provider
     */
    provider?: 'claude' | 'local' | 'google';
    /**
     * Embedding Model
     */
    embedding_model?: string | null;
    /**
     * Match Threshold
     */
    match_threshold?: number;
    /**
     * Record Index
     */
    record_index?: number;
    /**
     * Record Id
     */
    record_id?: string | null;
};

/**
 * BidFitResponse
 */
export type BidFitResponse = {
    /**
     * Hardliners
     */
    hardliners: Array<string>;
    /**
     * Violations
     */
    violations: Array<HardlinerViolation>;
    /**
     * Flag
     */
    flag: string;
    /**
     * Similarity Score
     */
    similarity_score: number;
    /**
     * Hard Blockers
     */
    hard_blockers: Array<string>;
    /**
     * Soft Issues
     */
    soft_issues: Array<string>;
};

/**
 * BidFitScore
 *
 * Final verdict for one bid against one company profile.
 *
 * `flag` is the go/no-go signal and is decided purely from the hardliner
 * violations — it never blends in similarity, so a topically "similar"
 * bid can never talk its way past an unresolved dealbreaker:
 *
 * - red: at least one violated hardliner has no realistic solution —
 * not worth pursuing.
 * - yellow: every violation has a realistic solution — workable, but
 * flag the mitigations needed.
 * - green: no hardliner is violated at all.
 *
 * `similarity_score` (0-1 cosine similarity between the company's
 * profile/hardliners and the retrieved bid context) is reported
 * separately, purely to rank bids that share the same flag — it's not a
 * fit signal on its own.
 */
export type BidFitScore = {
    /**
     * Flag
     */
    flag: string;
    /**
     * Similarity Score
     */
    similarity_score: number;
    /**
     * Hard Blockers
     */
    hard_blockers: Array<string>;
    /**
     * Soft Issues
     */
    soft_issues: Array<string>;
};

/**
 * BidMatchResult
 */
export type BidMatchResult = {
    /**
     * Bid Id
     */
    bid_id: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Notice Identifier
     */
    notice_identifier?: string | null;
    /**
     * Hardliners
     */
    hardliners: Array<string>;
    /**
     * Violations
     */
    violations: Array<HardlinerViolation>;
    /**
     * Flag
     */
    flag: string;
    /**
     * Similarity Score
     */
    similarity_score: number;
    /**
     * Hard Blockers
     */
    hard_blockers: Array<string>;
    /**
     * Soft Issues
     */
    soft_issues: Array<string>;
};

/**
 * BidPublic
 */
export type BidPublic = {
    /**
     * Source File
     */
    source_file: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Notice Identifier
     */
    notice_identifier?: string | null;
    /**
     * Place Of Performance
     */
    place_of_performance?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * BidScreenRequest
 */
export type BidScreenRequest = {
    /**
     * Bid Source
     */
    bid_source?: string | null;
    /**
     * Bid Content
     */
    bid_content?: string | null;
    /**
     * Hardliners
     */
    hardliners: Array<string>;
    /**
     * Bid Loader
     */
    bid_loader: string;
    /**
     * Bid Chunker
     */
    bid_chunker?: string;
    /**
     * Top K
     */
    top_k?: number;
    /**
     * Provider
     */
    provider?: 'claude' | 'local' | 'google';
    /**
     * Embedding Model
     */
    embedding_model?: string | null;
    /**
     * Company Context
     */
    company_context?: string;
    /**
     * Profile Sections
     */
    profile_sections?: Array<string> | null;
    /**
     * Match Threshold
     */
    match_threshold?: number;
    /**
     * Record Index
     */
    record_index?: number;
    /**
     * Record Id
     */
    record_id?: string | null;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ChatMessage
 */
export type ChatMessage = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
};

/**
 * ChatRequest
 */
export type ChatRequest = {
    /**
     * Messages
     */
    messages: Array<ChatMessage>;
    /**
     * Provider
     */
    provider?: 'claude' | 'local' | 'google';
    /**
     * Language
     */
    language?: 'en' | 'de';
};

/**
 * ChatResponse
 */
export type ChatResponse = {
    /**
     * Content
     */
    content: string;
};

/**
 * ChunkRequest
 */
export type ChunkRequest = {
    /**
     * Text
     */
    text: string;
    /**
     * Chunker
     */
    chunker?: string;
};

/**
 * CompanyProfileCreate
 */
export type CompanyProfileCreate = {
    /**
     * Company Name
     */
    company_name: string;
    /**
     * Base Location
     */
    base_location?: string | null;
    /**
     * Founded Year
     */
    founded_year?: number | null;
    /**
     * Employee Count
     */
    employee_count?: number | null;
    /**
     * Annual Revenue Eur
     */
    annual_revenue_eur?: number | null;
    /**
     * Geographic Reach
     */
    geographic_reach?: string | null;
    /**
     * Contract Size
     */
    contract_size?: string | null;
    /**
     * Capabilities
     */
    capabilities?: string | null;
    /**
     * Exclusions
     */
    exclusions?: string | null;
    /**
     * Certifications
     */
    certifications?: string | null;
    /**
     * Contractor Role
     */
    contractor_role?: string | null;
    /**
     * Capacity
     */
    capacity?: string | null;
    /**
     * Reference Projects
     */
    reference_projects?: string | null;
    /**
     * Hardliners
     */
    hardliners?: string | null;
    /**
     * Self Description
     */
    self_description?: string | null;
};

/**
 * CompanyProfilePublic
 */
export type CompanyProfilePublic = {
    /**
     * Company Name
     */
    company_name: string;
    /**
     * Base Location
     */
    base_location?: string | null;
    /**
     * Founded Year
     */
    founded_year?: number | null;
    /**
     * Employee Count
     */
    employee_count?: number | null;
    /**
     * Annual Revenue Eur
     */
    annual_revenue_eur?: number | null;
    /**
     * Geographic Reach
     */
    geographic_reach?: string | null;
    /**
     * Contract Size
     */
    contract_size?: string | null;
    /**
     * Capabilities
     */
    capabilities?: string | null;
    /**
     * Exclusions
     */
    exclusions?: string | null;
    /**
     * Certifications
     */
    certifications?: string | null;
    /**
     * Contractor Role
     */
    contractor_role?: string | null;
    /**
     * Capacity
     */
    capacity?: string | null;
    /**
     * Reference Projects
     */
    reference_projects?: string | null;
    /**
     * Hardliners
     */
    hardliners?: string | null;
    /**
     * Self Description
     */
    self_description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * CompleteRequest
 */
export type CompleteRequest = {
    /**
     * Messages
     */
    messages: Array<{
        [key: string]: string;
    }>;
};

/**
 * CrawlWebsiteRequest
 */
export type CrawlWebsiteRequest = {
    /**
     * Url
     */
    url: string;
};

/**
 * ExtractHardlinersResponse
 */
export type ExtractHardlinersResponse = {
    /**
     * Hardliners
     */
    hardliners: Array<string>;
};

/**
 * ExtractRequest
 */
export type ExtractRequest = {
    /**
     * Url
     */
    url: string;
    /**
     * Json Schema
     */
    json_schema: {
        [key: string]: unknown;
    };
    /**
     * Prompt
     */
    prompt?: string | null;
};

/**
 * GenerateRequest
 */
export type GenerateRequest = {
    /**
     * Source
     */
    source: string;
    /**
     * Loader
     */
    loader: string;
    /**
     * Query
     */
    query: string;
    /**
     * Chunker
     */
    chunker?: string;
    /**
     * Top K
     */
    top_k?: number;
    /**
     * Use Retrieval
     */
    use_retrieval?: boolean;
    /**
     * Retrieval Method
     */
    retrieval_method?: string;
    /**
     * Embedding Model
     */
    embedding_model?: 'qwen3-embedding:0.6b' | 'nomic-embed-text' | 'bge-m3' | 'jina-embeddings-v3' | 'gemini-embedding-2-preview' | null;
};

/**
 * GenerateViolationsRequest
 */
export type GenerateViolationsRequest = {
    /**
     * Hardliners
     */
    hardliners: Array<string>;
    /**
     * Context Chunks
     */
    context_chunks: Array<string>;
    /**
     * Profile Text
     */
    profile_text?: string;
    /**
     * Bid Source
     */
    bid_source?: string;
    /**
     * Provider
     */
    provider?: 'claude' | 'local' | 'google';
};

/**
 * GenerateViolationsResponse
 */
export type GenerateViolationsResponse = {
    /**
     * Violations
     */
    violations: Array<HardlinerViolation>;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HardlinerViolation
 *
 * One hardliner checked against the bid, with the LLM's verdict.
 */
export type HardlinerViolation = {
    /**
     * Hardliner
     */
    hardliner: string;
    /**
     * Violated
     */
    violated: boolean;
    /**
     * Reason
     *
     * Why the bid does or doesn't satisfy this hardliner, grounded in the retrieved bid context.
     */
    reason: string;
    /**
     * Solution
     *
     * A concrete way to resolve the violation, if one realistically exists (e.g. subcontracting a missing capability). Omit if no viable solution exists.
     */
    solution?: string | null;
    /**
     * Solution Is Realistic
     *
     * False whenever `solution` is None, and also False if a proposed solution is impractical, too costly, or otherwise shouldn't count (e.g. 'get certified in two weeks' for a six-month certification process, or anything that would still break a non-negotiable hardliner).
     */
    solution_is_realistic?: boolean;
};

/**
 * IngestRequest
 */
export type IngestRequest = {
    /**
     * Source
     */
    source: string;
    /**
     * Loader
     */
    loader: string;
    /**
     * Chunker
     */
    chunker?: string;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * LoadRequest
 */
export type LoadRequest = {
    /**
     * Source
     */
    source: string;
    /**
     * Loader
     */
    loader: string;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * ProfileChatRequest
 */
export type ProfileChatRequest = {
    /**
     * Messages
     */
    messages: Array<ChatMessage>;
    /**
     * Provider
     */
    provider?: 'claude' | 'local' | 'google';
};

/**
 * ProfileChatResponse
 */
export type ProfileChatResponse = {
    /**
     * Content
     */
    content: string;
};

/**
 * ProfileSectionsResponse
 */
export type ProfileSectionsResponse = {
    /**
     * Profile Sections
     */
    profile_sections: Array<string>;
};

/**
 * RankBidFitsRequest
 */
export type RankBidFitsRequest = {
    /**
     * Results
     */
    results: Array<BidFitScore>;
};

/**
 * RankBidFitsResponse
 */
export type RankBidFitsResponse = {
    /**
     * Ranked
     */
    ranked: Array<BidFitScore>;
};

/**
 * RetrieveBidContextRequest
 */
export type RetrieveBidContextRequest = {
    /**
     * Bid Source
     */
    bid_source?: string | null;
    /**
     * Bid Content
     */
    bid_content?: string | null;
    /**
     * Profile Sections
     */
    profile_sections: Array<string>;
    /**
     * Bid Loader
     */
    bid_loader: string;
    /**
     * Bid Chunker
     */
    bid_chunker?: string;
    /**
     * Top K
     */
    top_k?: number;
    /**
     * Match Threshold
     */
    match_threshold?: number;
    /**
     * Embedding Model
     */
    embedding_model?: string | null;
    /**
     * Record Index
     */
    record_index?: number;
    /**
     * Record Id
     */
    record_id?: string | null;
};

/**
 * RetrieveBidContextResponse
 */
export type RetrieveBidContextResponse = {
    /**
     * Bid Metadata
     */
    bid_metadata: {
        [key: string]: unknown;
    };
    /**
     * Context Chunks
     */
    context_chunks: Array<string>;
    /**
     * Similarity Score
     */
    similarity_score: number;
};

/**
 * ScoreBidFitRequest
 */
export type ScoreBidFitRequest = {
    /**
     * Violations
     */
    violations: Array<HardlinerViolation>;
    /**
     * Similarity Score
     */
    similarity_score?: number;
};

/**
 * ScrapeWebsiteRequest
 */
export type ScrapeWebsiteRequest = {
    /**
     * Url
     */
    url: string;
};

/**
 * SearchRequest
 */
export type SearchRequest = {
    /**
     * Query
     */
    query: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type chatSendMessageData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chat/message';
};

export type chatSendMessageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type chatSendMessageError = chatSendMessageErrors[keyof chatSendMessageErrors];

export type chatSendMessageResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type chatSendMessageResponse = chatSendMessageResponses[keyof chatSendMessageResponses];

export type companyProfileDeleteCompanyProfileMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/company-profile/me';
};

export type companyProfileDeleteCompanyProfileMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type companyProfileDeleteCompanyProfileMeResponse = companyProfileDeleteCompanyProfileMeResponses[keyof companyProfileDeleteCompanyProfileMeResponses];

export type companyProfileReadCompanyProfileMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/company-profile/me';
};

export type companyProfileReadCompanyProfileMeResponses = {
    /**
     * Successful Response
     */
    200: CompanyProfilePublic;
};

export type companyProfileReadCompanyProfileMeResponse = companyProfileReadCompanyProfileMeResponses[keyof companyProfileReadCompanyProfileMeResponses];

export type companyProfileCreateCompanyProfileMeData = {
    body: CompanyProfileCreate;
    path?: never;
    query?: never;
    url: '/api/v1/company-profile/me';
};

export type companyProfileCreateCompanyProfileMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type companyProfileCreateCompanyProfileMeError = companyProfileCreateCompanyProfileMeErrors[keyof companyProfileCreateCompanyProfileMeErrors];

export type companyProfileCreateCompanyProfileMeResponses = {
    /**
     * Successful Response
     */
    200: CompanyProfilePublic;
};

export type companyProfileCreateCompanyProfileMeResponse = companyProfileCreateCompanyProfileMeResponses[keyof companyProfileCreateCompanyProfileMeResponses];

export type companyProfileSendProfileChatMessageData = {
    body: ProfileChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/company-profile/chat/message';
};

export type companyProfileSendProfileChatMessageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type companyProfileSendProfileChatMessageError = companyProfileSendProfileChatMessageErrors[keyof companyProfileSendProfileChatMessageErrors];

export type companyProfileSendProfileChatMessageResponses = {
    /**
     * Successful Response
     */
    200: ProfileChatResponse;
};

export type companyProfileSendProfileChatMessageResponse = companyProfileSendProfileChatMessageResponses[keyof companyProfileSendProfileChatMessageResponses];

export type companyProfileFinalizeCompanyProfileChatData = {
    body: ProfileChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/company-profile/chat/finalize';
};

export type companyProfileFinalizeCompanyProfileChatErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type companyProfileFinalizeCompanyProfileChatError = companyProfileFinalizeCompanyProfileChatErrors[keyof companyProfileFinalizeCompanyProfileChatErrors];

export type companyProfileFinalizeCompanyProfileChatResponses = {
    /**
     * Successful Response
     */
    200: CompanyProfilePublic;
};

export type companyProfileFinalizeCompanyProfileChatResponse = companyProfileFinalizeCompanyProfileChatResponses[keyof companyProfileFinalizeCompanyProfileChatResponses];

export type bidFitAnalyzeBidFitData = {
    body: BidFitRequest;
    path?: never;
    query?: never;
    url: '/api/v1/bid-fit/analyze';
};

export type bidFitAnalyzeBidFitErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type bidFitAnalyzeBidFitError = bidFitAnalyzeBidFitErrors[keyof bidFitAnalyzeBidFitErrors];

export type bidFitAnalyzeBidFitResponses = {
    /**
     * Successful Response
     */
    200: BidFitResponse;
};

export type bidFitAnalyzeBidFitResponse = bidFitAnalyzeBidFitResponses[keyof bidFitAnalyzeBidFitResponses];

export type bidFitScreenBidData = {
    body: BidScreenRequest;
    path?: never;
    query?: never;
    url: '/api/v1/bid-fit/screen';
};

export type bidFitScreenBidErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type bidFitScreenBidError = bidFitScreenBidErrors[keyof bidFitScreenBidErrors];

export type bidFitScreenBidResponses = {
    /**
     * Successful Response
     */
    200: BidFitResponse;
};

export type bidFitScreenBidResponse = bidFitScreenBidResponses[keyof bidFitScreenBidResponses];

export type bidFitAnalyzeBidsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Provider
         */
        provider?: 'claude' | 'local' | 'google';
        /**
         * Top N
         */
        top_n?: number;
    };
    url: '/api/v1/bid-fit/analyze-bids';
};

export type bidFitAnalyzeBidsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type bidFitAnalyzeBidsError = bidFitAnalyzeBidsErrors[keyof bidFitAnalyzeBidsErrors];

export type bidFitAnalyzeBidsResponses = {
    /**
     * Successful Response
     */
    200: AnalyzeBidsResponse;
};

export type bidFitAnalyzeBidsResponse = bidFitAnalyzeBidsResponses[keyof bidFitAnalyzeBidsResponses];

export type bidFitExtractHardlinersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/bid-fit/extract-hardliners';
};

export type bidFitExtractHardlinersResponses = {
    /**
     * Successful Response
     */
    200: ExtractHardlinersResponse;
};

export type bidFitExtractHardlinersResponse = bidFitExtractHardlinersResponses[keyof bidFitExtractHardlinersResponses];

export type bidFitProfileSectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/bid-fit/profile-sections';
};

export type bidFitProfileSectionsResponses = {
    /**
     * Successful Response
     */
    200: ProfileSectionsResponse;
};

export type bidFitProfileSectionsResponse = bidFitProfileSectionsResponses[keyof bidFitProfileSectionsResponses];

export type bidFitRetrieveData = {
    body: RetrieveBidContextRequest;
    path?: never;
    query?: never;
    url: '/api/v1/bid-fit/retrieve';
};

export type bidFitRetrieveErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type bidFitRetrieveError = bidFitRetrieveErrors[keyof bidFitRetrieveErrors];

export type bidFitRetrieveResponses = {
    /**
     * Successful Response
     */
    200: RetrieveBidContextResponse;
};

export type bidFitRetrieveResponse = bidFitRetrieveResponses[keyof bidFitRetrieveResponses];

export type bidFitGenerateViolationsEndpointData = {
    body: GenerateViolationsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/bid-fit/generate-violations';
};

export type bidFitGenerateViolationsEndpointErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type bidFitGenerateViolationsEndpointError = bidFitGenerateViolationsEndpointErrors[keyof bidFitGenerateViolationsEndpointErrors];

export type bidFitGenerateViolationsEndpointResponses = {
    /**
     * Successful Response
     */
    200: GenerateViolationsResponse;
};

export type bidFitGenerateViolationsEndpointResponse = bidFitGenerateViolationsEndpointResponses[keyof bidFitGenerateViolationsEndpointResponses];

export type bidFitScoreData = {
    body: ScoreBidFitRequest;
    path?: never;
    query?: never;
    url: '/api/v1/bid-fit/score';
};

export type bidFitScoreErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type bidFitScoreError = bidFitScoreErrors[keyof bidFitScoreErrors];

export type bidFitScoreResponses = {
    /**
     * Successful Response
     */
    200: BidFitScore;
};

export type bidFitScoreResponse = bidFitScoreResponses[keyof bidFitScoreResponses];

export type bidFitRankData = {
    body: RankBidFitsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/bid-fit/rank';
};

export type bidFitRankErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type bidFitRankError = bidFitRankErrors[keyof bidFitRankErrors];

export type bidFitRankResponses = {
    /**
     * Successful Response
     */
    200: RankBidFitsResponse;
};

export type bidFitRankResponse = bidFitRankResponses[keyof bidFitRankResponses];

export type bidsListBidsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/bids/';
};

export type bidsListBidsResponses = {
    /**
     * Response Bids-List Bids
     *
     * Successful Response
     */
    200: Array<BidPublic>;
};

export type bidsListBidsResponse = bidsListBidsResponses[keyof bidsListBidsResponses];

export type bidsLoadBidsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/bids/load';
};

export type bidsLoadBidsResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type bidsLoadBidsResponse = bidsLoadBidsResponses[keyof bidsLoadBidsResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];

export type toolsLoadSourceData = {
    body: LoadRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/rag/load';
};

export type toolsLoadSourceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsLoadSourceError = toolsLoadSourceErrors[keyof toolsLoadSourceErrors];

export type toolsLoadSourceResponses = {
    /**
     * Response Tools-Load Source
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsLoadSourceResponse = toolsLoadSourceResponses[keyof toolsLoadSourceResponses];

export type toolsChunkTextData = {
    body: ChunkRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/rag/chunk';
};

export type toolsChunkTextErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsChunkTextError = toolsChunkTextErrors[keyof toolsChunkTextErrors];

export type toolsChunkTextResponses = {
    /**
     * Response Tools-Chunk Text
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsChunkTextResponse = toolsChunkTextResponses[keyof toolsChunkTextResponses];

export type toolsIngestSourceData = {
    body: IngestRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/rag/ingest';
};

export type toolsIngestSourceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsIngestSourceError = toolsIngestSourceErrors[keyof toolsIngestSourceErrors];

export type toolsIngestSourceResponses = {
    /**
     * Response Tools-Ingest Source
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsIngestSourceResponse = toolsIngestSourceResponses[keyof toolsIngestSourceResponses];

export type toolsCompleteData = {
    body: CompleteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/llm/complete';
};

export type toolsCompleteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsCompleteError = toolsCompleteErrors[keyof toolsCompleteErrors];

export type toolsCompleteResponses = {
    /**
     * Response Tools-Complete
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type toolsCompleteResponse = toolsCompleteResponses[keyof toolsCompleteResponses];

export type toolsGenerateData = {
    body: GenerateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/rag/generate';
};

export type toolsGenerateErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsGenerateError = toolsGenerateErrors[keyof toolsGenerateErrors];

export type toolsGenerateResponses = {
    /**
     * Response Tools-Generate
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsGenerateResponse = toolsGenerateResponses[keyof toolsGenerateResponses];

export type toolsCrawlWebsiteData = {
    body: CrawlWebsiteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/firecrawl/crawl';
};

export type toolsCrawlWebsiteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsCrawlWebsiteError = toolsCrawlWebsiteErrors[keyof toolsCrawlWebsiteErrors];

export type toolsCrawlWebsiteResponses = {
    /**
     * Response Tools-Crawl Website
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsCrawlWebsiteResponse = toolsCrawlWebsiteResponses[keyof toolsCrawlWebsiteResponses];

export type toolsScrapeWebsiteData = {
    body: ScrapeWebsiteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/firecrawl/scrape';
};

export type toolsScrapeWebsiteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsScrapeWebsiteError = toolsScrapeWebsiteErrors[keyof toolsScrapeWebsiteErrors];

export type toolsScrapeWebsiteResponses = {
    /**
     * Response Tools-Scrape Website
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsScrapeWebsiteResponse = toolsScrapeWebsiteResponses[keyof toolsScrapeWebsiteResponses];

export type toolsSearchData = {
    body: SearchRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/firecrawl/search';
};

export type toolsSearchErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsSearchError = toolsSearchErrors[keyof toolsSearchErrors];

export type toolsSearchResponses = {
    /**
     * Response Tools-Search
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsSearchResponse = toolsSearchResponses[keyof toolsSearchResponses];

export type toolsExtractData = {
    body: ExtractRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/firecrawl/extract';
};

export type toolsExtractErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsExtractError = toolsExtractErrors[keyof toolsExtractErrors];

export type toolsExtractResponses = {
    /**
     * Response Tools-Extract
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsExtractResponse = toolsExtractResponses[keyof toolsExtractResponses];
