// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CapitalEfficiencyPeriod
 */
export type CapitalEfficiencyPeriod = {
    /**
     * Filing Id
     */
    filing_id: string;
    /**
     * Period End
     */
    period_end: string | null;
    /**
     * Invested Capital
     */
    invested_capital: number | null;
    /**
     * Roic Pct
     */
    roic_pct: number | null;
    /**
     * Effective Tax Rate
     */
    effective_tax_rate: number | null;
    /**
     * Capex Pct Of Revenue
     */
    capex_pct_of_revenue: number | null;
};

/**
 * CapitalEfficiencyTrend
 */
export type CapitalEfficiencyTrend = {
    /**
     * Filing Id
     */
    filing_id: string;
    /**
     * Periods
     */
    periods: Array<CapitalEfficiencyPeriod>;
};

/**
 * ChatMessage
 */
export type ChatMessage = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
};

/**
 * ChatRequest
 */
export type ChatRequest = {
    /**
     * Messages
     */
    messages: Array<ChatMessage>;
    /**
     * Provider
     */
    provider?: 'claude' | 'local';
};

/**
 * ChatResponse
 */
export type ChatResponse = {
    /**
     * Content
     */
    content: string;
};

/**
 * ChunkRequest
 */
export type ChunkRequest = {
    /**
     * Text
     */
    text: string;
    /**
     * Chunker
     */
    chunker?: string;
};

/**
 * CompaniesPublic
 */
export type CompaniesPublic = {
    /**
     * Data
     */
    data: Array<CompanyPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * CompanyDirectoryEntry
 */
export type CompanyDirectoryEntry = {
    /**
     * Cik
     */
    cik: string;
    /**
     * Ticker
     */
    ticker: string;
    /**
     * Name
     */
    name: string;
};

/**
 * CompanyPublic
 */
export type CompanyPublic = {
    /**
     * Cik
     */
    cik: string;
    /**
     * Name
     */
    name: string;
    /**
     * Ticker
     */
    ticker?: string | null;
    /**
     * Sic Code
     */
    sic_code?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * CompanyTimeline
 */
export type CompanyTimeline = {
    company: CompanyPublic;
    /**
     * Filings
     */
    filings: Array<FilingTimelineEntry>;
};

/**
 * CompleteRequest
 */
export type CompleteRequest = {
    /**
     * Messages
     */
    messages: Array<{
        [key: string]: string;
    }>;
};

/**
 * CrawlWebsiteRequest
 */
export type CrawlWebsiteRequest = {
    /**
     * Url
     */
    url: string;
};

/**
 * DilutionPeriod
 */
export type DilutionPeriod = {
    /**
     * Filing Id
     */
    filing_id: string;
    /**
     * Period End
     */
    period_end: string | null;
    /**
     * Share Count
     */
    share_count: number | null;
    /**
     * Share Count Change Pct
     */
    share_count_change_pct: number | null;
    /**
     * Sbc
     */
    sbc: number | null;
    /**
     * Operating Cash Flow
     */
    operating_cash_flow: number | null;
    /**
     * Sbc Pct Of Operating Cash Flow
     */
    sbc_pct_of_operating_cash_flow: number | null;
};

/**
 * DilutionTrend
 */
export type DilutionTrend = {
    /**
     * Filing Id
     */
    filing_id: string;
    /**
     * Periods
     */
    periods: Array<DilutionPeriod>;
};

/**
 * ExtractRequest
 */
export type ExtractRequest = {
    /**
     * Url
     */
    url: string;
    /**
     * Json Schema
     */
    json_schema: {
        [key: string]: unknown;
    };
    /**
     * Prompt
     */
    prompt?: string | null;
};

/**
 * FilingPublic
 */
export type FilingPublic = {
    /**
     * Accession Number
     */
    accession_number: string;
    /**
     * Form Type
     */
    form_type: string;
    /**
     * Filing Date
     */
    filing_date: string;
    /**
     * Period Of Report
     */
    period_of_report?: string | null;
    /**
     * Primary Document
     */
    primary_document?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Company Id
     */
    company_id: string;
    /**
     * Previous Filing Id
     */
    previous_filing_id?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * FilingSignals
 */
export type FilingSignals = {
    /**
     * Filing Id
     */
    filing_id: string;
    /**
     * Previous Filing Id
     */
    previous_filing_id: string | null;
    /**
     * Debt And Liquidity
     */
    debt_and_liquidity: Array<MetricChange>;
    capex: MetricChange;
};

/**
 * FilingTimelineEntry
 */
export type FilingTimelineEntry = {
    /**
     * Filing Id
     */
    filing_id: string;
    /**
     * Accession Number
     */
    accession_number: string;
    /**
     * Form Type
     */
    form_type: string;
    /**
     * Filing Date
     */
    filing_date: string;
    /**
     * Period Of Report
     */
    period_of_report: string | null;
    signals: FilingSignals | null;
    /**
     * Narrative Changes
     */
    narrative_changes: Array<NarrativeChangePublic>;
    structured_risk_flags: StructuredRiskFlags | null;
};

/**
 * FilingsPublic
 */
export type FilingsPublic = {
    /**
     * Data
     */
    data: Array<FilingPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * FinancialFactPublic
 */
export type FinancialFactPublic = {
    /**
     * Taxonomy
     */
    taxonomy: string;
    /**
     * Concept
     */
    concept: string;
    /**
     * Unit
     */
    unit: string;
    /**
     * Value
     */
    value: number;
    /**
     * Fiscal Year
     */
    fiscal_year?: number | null;
    /**
     * Fiscal Period
     */
    fiscal_period?: string | null;
    /**
     * Period Start
     */
    period_start?: string | null;
    /**
     * Period End
     */
    period_end?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Filing Id
     */
    filing_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * FinancialFactsPublic
 */
export type FinancialFactsPublic = {
    /**
     * Data
     */
    data: Array<FinancialFactPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * GenerateRequest
 */
export type GenerateRequest = {
    /**
     * Source
     */
    source: string;
    /**
     * Loader
     */
    loader: string;
    /**
     * Query
     */
    query: string;
    /**
     * Chunker
     */
    chunker?: string;
    /**
     * Top K
     */
    top_k?: number;
    /**
     * Use Retrieval
     */
    use_retrieval?: boolean;
    /**
     * Retrieval Method
     */
    retrieval_method?: string;
    /**
     * Embedding Model
     */
    embedding_model?: string | null;
};

/**
 * GrossMarginPeriod
 */
export type GrossMarginPeriod = {
    /**
     * Filing Id
     */
    filing_id: string;
    /**
     * Period End
     */
    period_end: string | null;
    /**
     * Revenue
     */
    revenue: number | null;
    /**
     * Revenue Change Pct
     */
    revenue_change_pct: number | null;
    /**
     * Gross Profit
     */
    gross_profit: number | null;
    /**
     * Gross Margin Pct
     */
    gross_margin_pct: number | null;
    /**
     * Gross Margin Change Pct Points
     */
    gross_margin_change_pct_points: number | null;
    /**
     * Margin Compressed While Revenue Grew
     */
    margin_compressed_while_revenue_grew: boolean | null;
};

/**
 * GrossMarginTrend
 */
export type GrossMarginTrend = {
    /**
     * Filing Id
     */
    filing_id: string;
    /**
     * Periods
     */
    periods: Array<GrossMarginPeriod>;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IngestRequest
 */
export type IngestRequest = {
    /**
     * Source
     */
    source: string;
    /**
     * Loader
     */
    loader: string;
    /**
     * Chunker
     */
    chunker?: string;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * LoadRequest
 */
export type LoadRequest = {
    /**
     * Source
     */
    source: string;
    /**
     * Loader
     */
    loader: string;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * MetricChange
 */
export type MetricChange = {
    /**
     * Metric
     */
    metric: string;
    /**
     * Unit
     */
    unit: string;
    /**
     * Current Value
     */
    current_value: number | null;
    /**
     * Previous Value
     */
    previous_value: number | null;
    /**
     * Change
     */
    change: number | null;
    /**
     * Change Pct
     */
    change_pct: number | null;
};

/**
 * NarrativeChangePublic
 */
export type NarrativeChangePublic = {
    /**
     * Section Type
     */
    section_type: string;
    /**
     * Change Type
     */
    change_type: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Similarity Score
     */
    similarity_score?: number | null;
    /**
     * New Excerpt
     */
    new_excerpt?: string | null;
    /**
     * Old Excerpt
     */
    old_excerpt?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Filing Id
     */
    filing_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * NarrativeChangesPublic
 */
export type NarrativeChangesPublic = {
    /**
     * Data
     */
    data: Array<NarrativeChangePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * RiskFlag
 */
export type RiskFlag = {
    /**
     * Flag Type
     */
    flag_type: string;
    /**
     * Message
     */
    message: string;
};

/**
 * ScrapeWebsiteRequest
 */
export type ScrapeWebsiteRequest = {
    /**
     * Url
     */
    url: string;
};

/**
 * SearchRequest
 */
export type SearchRequest = {
    /**
     * Query
     */
    query: string;
};

/**
 * StructuredRiskFlags
 */
export type StructuredRiskFlags = {
    /**
     * Filing Id
     */
    filing_id: string;
    /**
     * Flags
     */
    flags: Array<RiskFlag>;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type chatSendMessageData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chat/message';
};

export type chatSendMessageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type chatSendMessageError = chatSendMessageErrors[keyof chatSendMessageErrors];

export type chatSendMessageResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type chatSendMessageResponse = chatSendMessageResponses[keyof chatSendMessageResponses];

export type ingestionSyncCompanyData = {
    body?: never;
    path: {
        /**
         * Cik
         */
        cik: string;
    };
    query?: never;
    url: '/api/v1/ingestion/companies/{cik}/sync';
};

export type ingestionSyncCompanyErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ingestionSyncCompanyError = ingestionSyncCompanyErrors[keyof ingestionSyncCompanyErrors];

export type ingestionSyncCompanyResponses = {
    /**
     * Successful Response
     */
    200: CompanyPublic;
};

export type ingestionSyncCompanyResponse = ingestionSyncCompanyResponses[keyof ingestionSyncCompanyResponses];

export type ingestionListFilingsData = {
    body?: never;
    path: {
        /**
         * Cik
         */
        cik: string;
    };
    query?: never;
    url: '/api/v1/ingestion/companies/{cik}/filings';
};

export type ingestionListFilingsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ingestionListFilingsError = ingestionListFilingsErrors[keyof ingestionListFilingsErrors];

export type ingestionListFilingsResponses = {
    /**
     * Successful Response
     */
    200: FilingsPublic;
};

export type ingestionListFilingsResponse = ingestionListFilingsResponses[keyof ingestionListFilingsResponses];

export type ingestionListFactsData = {
    body?: never;
    path: {
        /**
         * Filing Id
         */
        filing_id: string;
    };
    query?: never;
    url: '/api/v1/ingestion/filings/{filing_id}/facts';
};

export type ingestionListFactsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ingestionListFactsError = ingestionListFactsErrors[keyof ingestionListFactsErrors];

export type ingestionListFactsResponses = {
    /**
     * Successful Response
     */
    200: FinancialFactsPublic;
};

export type ingestionListFactsResponse = ingestionListFactsResponses[keyof ingestionListFactsResponses];

export type ingestionGetSignalsData = {
    body?: never;
    path: {
        /**
         * Filing Id
         */
        filing_id: string;
    };
    query?: never;
    url: '/api/v1/ingestion/filings/{filing_id}/signals';
};

export type ingestionGetSignalsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ingestionGetSignalsError = ingestionGetSignalsErrors[keyof ingestionGetSignalsErrors];

export type ingestionGetSignalsResponses = {
    /**
     * Successful Response
     */
    200: FilingSignals;
};

export type ingestionGetSignalsResponse = ingestionGetSignalsResponses[keyof ingestionGetSignalsResponses];

export type ingestionGetDilutionTrendRouteData = {
    body?: never;
    path: {
        /**
         * Filing Id
         */
        filing_id: string;
    };
    query?: never;
    url: '/api/v1/ingestion/filings/{filing_id}/dilution-trend';
};

export type ingestionGetDilutionTrendRouteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ingestionGetDilutionTrendRouteError = ingestionGetDilutionTrendRouteErrors[keyof ingestionGetDilutionTrendRouteErrors];

export type ingestionGetDilutionTrendRouteResponses = {
    /**
     * Successful Response
     */
    200: DilutionTrend;
};

export type ingestionGetDilutionTrendRouteResponse = ingestionGetDilutionTrendRouteResponses[keyof ingestionGetDilutionTrendRouteResponses];

export type ingestionGetGrossMarginTrendRouteData = {
    body?: never;
    path: {
        /**
         * Filing Id
         */
        filing_id: string;
    };
    query?: never;
    url: '/api/v1/ingestion/filings/{filing_id}/gross-margin-trend';
};

export type ingestionGetGrossMarginTrendRouteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ingestionGetGrossMarginTrendRouteError = ingestionGetGrossMarginTrendRouteErrors[keyof ingestionGetGrossMarginTrendRouteErrors];

export type ingestionGetGrossMarginTrendRouteResponses = {
    /**
     * Successful Response
     */
    200: GrossMarginTrend;
};

export type ingestionGetGrossMarginTrendRouteResponse = ingestionGetGrossMarginTrendRouteResponses[keyof ingestionGetGrossMarginTrendRouteResponses];

export type ingestionGetCapitalEfficiencyTrendRouteData = {
    body?: never;
    path: {
        /**
         * Filing Id
         */
        filing_id: string;
    };
    query?: never;
    url: '/api/v1/ingestion/filings/{filing_id}/capital-efficiency-trend';
};

export type ingestionGetCapitalEfficiencyTrendRouteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ingestionGetCapitalEfficiencyTrendRouteError = ingestionGetCapitalEfficiencyTrendRouteErrors[keyof ingestionGetCapitalEfficiencyTrendRouteErrors];

export type ingestionGetCapitalEfficiencyTrendRouteResponses = {
    /**
     * Successful Response
     */
    200: CapitalEfficiencyTrend;
};

export type ingestionGetCapitalEfficiencyTrendRouteResponse = ingestionGetCapitalEfficiencyTrendRouteResponses[keyof ingestionGetCapitalEfficiencyTrendRouteResponses];

export type ingestionGetStructuredRiskFlagsRouteData = {
    body?: never;
    path: {
        /**
         * Filing Id
         */
        filing_id: string;
    };
    query?: never;
    url: '/api/v1/ingestion/filings/{filing_id}/structured-risk-flags';
};

export type ingestionGetStructuredRiskFlagsRouteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ingestionGetStructuredRiskFlagsRouteError = ingestionGetStructuredRiskFlagsRouteErrors[keyof ingestionGetStructuredRiskFlagsRouteErrors];

export type ingestionGetStructuredRiskFlagsRouteResponses = {
    /**
     * Successful Response
     */
    200: StructuredRiskFlags;
};

export type ingestionGetStructuredRiskFlagsRouteResponse = ingestionGetStructuredRiskFlagsRouteResponses[keyof ingestionGetStructuredRiskFlagsRouteResponses];

export type ingestionComputeNarrativeDiffData = {
    body?: never;
    path: {
        /**
         * Filing Id
         */
        filing_id: string;
    };
    query: {
        /**
         * Section Type
         */
        section_type: 'risk_factors' | 'legal_proceedings';
    };
    url: '/api/v1/ingestion/filings/{filing_id}/narrative-diff';
};

export type ingestionComputeNarrativeDiffErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ingestionComputeNarrativeDiffError = ingestionComputeNarrativeDiffErrors[keyof ingestionComputeNarrativeDiffErrors];

export type ingestionComputeNarrativeDiffResponses = {
    /**
     * Successful Response
     */
    200: NarrativeChangesPublic;
};

export type ingestionComputeNarrativeDiffResponse = ingestionComputeNarrativeDiffResponses[keyof ingestionComputeNarrativeDiffResponses];

export type ingestionListNarrativeChangesData = {
    body?: never;
    path: {
        /**
         * Filing Id
         */
        filing_id: string;
    };
    query?: never;
    url: '/api/v1/ingestion/filings/{filing_id}/narrative-changes';
};

export type ingestionListNarrativeChangesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ingestionListNarrativeChangesError = ingestionListNarrativeChangesErrors[keyof ingestionListNarrativeChangesErrors];

export type ingestionListNarrativeChangesResponses = {
    /**
     * Successful Response
     */
    200: NarrativeChangesPublic;
};

export type ingestionListNarrativeChangesResponse = ingestionListNarrativeChangesResponses[keyof ingestionListNarrativeChangesResponses];

export type companiesSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
    };
    url: '/api/v1/companies/search';
};

export type companiesSearchErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type companiesSearchError = companiesSearchErrors[keyof companiesSearchErrors];

export type companiesSearchResponses = {
    /**
     * Response Companies-Search
     *
     * Successful Response
     */
    200: Array<CompanyDirectoryEntry>;
};

export type companiesSearchResponse = companiesSearchResponses[keyof companiesSearchResponses];

export type companiesGetTimelineData = {
    body?: never;
    path: {
        /**
         * Cik
         */
        cik: string;
    };
    query?: never;
    url: '/api/v1/companies/{cik}/timeline';
};

export type companiesGetTimelineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type companiesGetTimelineError = companiesGetTimelineErrors[keyof companiesGetTimelineErrors];

export type companiesGetTimelineResponses = {
    /**
     * Successful Response
     */
    200: CompanyTimeline;
};

export type companiesGetTimelineResponse = companiesGetTimelineResponses[keyof companiesGetTimelineResponses];

export type watchlistListWatchlistData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/watchlist';
};

export type watchlistListWatchlistResponses = {
    /**
     * Successful Response
     */
    200: CompaniesPublic;
};

export type watchlistListWatchlistResponse = watchlistListWatchlistResponses[keyof watchlistListWatchlistResponses];

export type watchlistRemoveFromWatchlistData = {
    body?: never;
    path: {
        /**
         * Cik
         */
        cik: string;
    };
    query?: never;
    url: '/api/v1/watchlist/{cik}';
};

export type watchlistRemoveFromWatchlistErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type watchlistRemoveFromWatchlistError = watchlistRemoveFromWatchlistErrors[keyof watchlistRemoveFromWatchlistErrors];

export type watchlistRemoveFromWatchlistResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type watchlistRemoveFromWatchlistResponse = watchlistRemoveFromWatchlistResponses[keyof watchlistRemoveFromWatchlistResponses];

export type watchlistAddToWatchlistData = {
    body?: never;
    path: {
        /**
         * Cik
         */
        cik: string;
    };
    query?: never;
    url: '/api/v1/watchlist/{cik}';
};

export type watchlistAddToWatchlistErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type watchlistAddToWatchlistError = watchlistAddToWatchlistErrors[keyof watchlistAddToWatchlistErrors];

export type watchlistAddToWatchlistResponses = {
    /**
     * Successful Response
     */
    200: CompanyPublic;
};

export type watchlistAddToWatchlistResponse = watchlistAddToWatchlistResponses[keyof watchlistAddToWatchlistResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];

export type toolsLoadSourceData = {
    body: LoadRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/rag/load';
};

export type toolsLoadSourceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsLoadSourceError = toolsLoadSourceErrors[keyof toolsLoadSourceErrors];

export type toolsLoadSourceResponses = {
    /**
     * Response Tools-Load Source
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsLoadSourceResponse = toolsLoadSourceResponses[keyof toolsLoadSourceResponses];

export type toolsChunkTextData = {
    body: ChunkRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/rag/chunk';
};

export type toolsChunkTextErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsChunkTextError = toolsChunkTextErrors[keyof toolsChunkTextErrors];

export type toolsChunkTextResponses = {
    /**
     * Response Tools-Chunk Text
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsChunkTextResponse = toolsChunkTextResponses[keyof toolsChunkTextResponses];

export type toolsIngestSourceData = {
    body: IngestRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/rag/ingest';
};

export type toolsIngestSourceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsIngestSourceError = toolsIngestSourceErrors[keyof toolsIngestSourceErrors];

export type toolsIngestSourceResponses = {
    /**
     * Response Tools-Ingest Source
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsIngestSourceResponse = toolsIngestSourceResponses[keyof toolsIngestSourceResponses];

export type toolsCompleteData = {
    body: CompleteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/llm/complete';
};

export type toolsCompleteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsCompleteError = toolsCompleteErrors[keyof toolsCompleteErrors];

export type toolsCompleteResponses = {
    /**
     * Response Tools-Complete
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type toolsCompleteResponse = toolsCompleteResponses[keyof toolsCompleteResponses];

export type toolsGenerateData = {
    body: GenerateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/rag/generate';
};

export type toolsGenerateErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsGenerateError = toolsGenerateErrors[keyof toolsGenerateErrors];

export type toolsGenerateResponses = {
    /**
     * Response Tools-Generate
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsGenerateResponse = toolsGenerateResponses[keyof toolsGenerateResponses];

export type toolsCrawlWebsiteData = {
    body: CrawlWebsiteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/firecrawl/crawl';
};

export type toolsCrawlWebsiteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsCrawlWebsiteError = toolsCrawlWebsiteErrors[keyof toolsCrawlWebsiteErrors];

export type toolsCrawlWebsiteResponses = {
    /**
     * Response Tools-Crawl Website
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsCrawlWebsiteResponse = toolsCrawlWebsiteResponses[keyof toolsCrawlWebsiteResponses];

export type toolsScrapeWebsiteData = {
    body: ScrapeWebsiteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/firecrawl/scrape';
};

export type toolsScrapeWebsiteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsScrapeWebsiteError = toolsScrapeWebsiteErrors[keyof toolsScrapeWebsiteErrors];

export type toolsScrapeWebsiteResponses = {
    /**
     * Response Tools-Scrape Website
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsScrapeWebsiteResponse = toolsScrapeWebsiteResponses[keyof toolsScrapeWebsiteResponses];

export type toolsSearchData = {
    body: SearchRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/firecrawl/search';
};

export type toolsSearchErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsSearchError = toolsSearchErrors[keyof toolsSearchErrors];

export type toolsSearchResponses = {
    /**
     * Response Tools-Search
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsSearchResponse = toolsSearchResponses[keyof toolsSearchResponses];

export type toolsExtractData = {
    body: ExtractRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/firecrawl/extract';
};

export type toolsExtractErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsExtractError = toolsExtractErrors[keyof toolsExtractErrors];

export type toolsExtractResponses = {
    /**
     * Response Tools-Extract
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsExtractResponse = toolsExtractResponses[keyof toolsExtractResponses];
