// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ChatMessage
 */
export type ChatMessage = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
};

/**
 * ChatRequest
 */
export type ChatRequest = {
    /**
     * Messages
     */
    messages: Array<ChatMessage>;
    /**
     * Provider
     */
    provider?: 'claude' | 'local';
};

/**
 * ChatResponse
 */
export type ChatResponse = {
    /**
     * Content
     */
    content: string;
};

/**
 * ChunkRequest
 */
export type ChunkRequest = {
    /**
     * Text
     */
    text: string;
    /**
     * Chunker
     */
    chunker?: string;
};

/**
 * CompanyProfileCreate
 */
export type CompanyProfileCreate = {
    /**
     * Company Name
     */
    company_name: string;
    /**
     * Base Location
     */
    base_location?: string | null;
    /**
     * Founded Year
     */
    founded_year?: number | null;
    /**
     * Employee Count
     */
    employee_count?: number | null;
    /**
     * Annual Revenue Eur
     */
    annual_revenue_eur?: number | null;
    /**
     * Max Radius Km
     */
    max_radius_km?: number | null;
    /**
     * Served Regions
     */
    served_regions?: Array<string>;
    /**
     * Excluded Regions
     */
    excluded_regions?: Array<string>;
    /**
     * Min Contract Value Eur
     */
    min_contract_value_eur?: number | null;
    /**
     * Max Contract Value Eur
     */
    max_contract_value_eur?: number | null;
    /**
     * Partner Threshold Eur
     */
    partner_threshold_eur?: number | null;
    /**
     * Capabilities
     */
    capabilities?: Array<string>;
    /**
     * Explicit Exclusions
     */
    explicit_exclusions?: Array<string>;
    /**
     * Certifications
     */
    certifications?: Array<string>;
    /**
     * Contractor Role
     */
    contractor_role?: string | null;
    /**
     * Max Self Perform Pct
     */
    max_self_perform_pct?: number | null;
    /**
     * Guarantee Limit Total Eur
     */
    guarantee_limit_total_eur?: number | null;
    /**
     * Guarantee Currently Committed Eur
     */
    guarantee_currently_committed_eur?: number | null;
    /**
     * Available From
     */
    available_from?: string | null;
    /**
     * Capacity Note
     */
    capacity_note?: string | null;
    /**
     * Reference Projects
     */
    reference_projects?: Array<string>;
    /**
     * Custom Hardliners
     */
    custom_hardliners?: Array<string>;
};

/**
 * CompanyProfilePublic
 */
export type CompanyProfilePublic = {
    /**
     * Company Name
     */
    company_name: string;
    /**
     * Base Location
     */
    base_location?: string | null;
    /**
     * Founded Year
     */
    founded_year?: number | null;
    /**
     * Employee Count
     */
    employee_count?: number | null;
    /**
     * Annual Revenue Eur
     */
    annual_revenue_eur?: number | null;
    /**
     * Max Radius Km
     */
    max_radius_km?: number | null;
    /**
     * Served Regions
     */
    served_regions?: Array<string>;
    /**
     * Excluded Regions
     */
    excluded_regions?: Array<string>;
    /**
     * Min Contract Value Eur
     */
    min_contract_value_eur?: number | null;
    /**
     * Max Contract Value Eur
     */
    max_contract_value_eur?: number | null;
    /**
     * Partner Threshold Eur
     */
    partner_threshold_eur?: number | null;
    /**
     * Capabilities
     */
    capabilities?: Array<string>;
    /**
     * Explicit Exclusions
     */
    explicit_exclusions?: Array<string>;
    /**
     * Certifications
     */
    certifications?: Array<string>;
    /**
     * Contractor Role
     */
    contractor_role?: string | null;
    /**
     * Max Self Perform Pct
     */
    max_self_perform_pct?: number | null;
    /**
     * Guarantee Limit Total Eur
     */
    guarantee_limit_total_eur?: number | null;
    /**
     * Guarantee Currently Committed Eur
     */
    guarantee_currently_committed_eur?: number | null;
    /**
     * Available From
     */
    available_from?: string | null;
    /**
     * Capacity Note
     */
    capacity_note?: string | null;
    /**
     * Reference Projects
     */
    reference_projects?: Array<string>;
    /**
     * Custom Hardliners
     */
    custom_hardliners?: Array<string>;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * CompleteRequest
 */
export type CompleteRequest = {
    /**
     * Messages
     */
    messages: Array<{
        [key: string]: string;
    }>;
};

/**
 * CrawlWebsiteRequest
 */
export type CrawlWebsiteRequest = {
    /**
     * Url
     */
    url: string;
};

/**
 * ExtractRequest
 */
export type ExtractRequest = {
    /**
     * Url
     */
    url: string;
    /**
     * Json Schema
     */
    json_schema: {
        [key: string]: unknown;
    };
    /**
     * Prompt
     */
    prompt?: string | null;
};

/**
 * GenerateRequest
 */
export type GenerateRequest = {
    /**
     * Source
     */
    source: string;
    /**
     * Loader
     */
    loader: string;
    /**
     * Query
     */
    query: string;
    /**
     * Chunker
     */
    chunker?: string;
    /**
     * Top K
     */
    top_k?: number;
    /**
     * Use Retrieval
     */
    use_retrieval?: boolean;
    /**
     * Retrieval Method
     */
    retrieval_method?: string;
    /**
     * Embedding Model
     */
    embedding_model?: string | null;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IngestRequest
 */
export type IngestRequest = {
    /**
     * Source
     */
    source: string;
    /**
     * Loader
     */
    loader: string;
    /**
     * Chunker
     */
    chunker?: string;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * LoadRequest
 */
export type LoadRequest = {
    /**
     * Source
     */
    source: string;
    /**
     * Loader
     */
    loader: string;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * ScrapeWebsiteRequest
 */
export type ScrapeWebsiteRequest = {
    /**
     * Url
     */
    url: string;
};

/**
 * SearchRequest
 */
export type SearchRequest = {
    /**
     * Query
     */
    query: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type chatSendMessageData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chat/message';
};

export type chatSendMessageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type chatSendMessageError = chatSendMessageErrors[keyof chatSendMessageErrors];

export type chatSendMessageResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type chatSendMessageResponse = chatSendMessageResponses[keyof chatSendMessageResponses];

export type companyProfileReadCompanyProfileMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/company-profile/me';
};

export type companyProfileReadCompanyProfileMeResponses = {
    /**
     * Successful Response
     */
    200: CompanyProfilePublic;
};

export type companyProfileReadCompanyProfileMeResponse = companyProfileReadCompanyProfileMeResponses[keyof companyProfileReadCompanyProfileMeResponses];

export type companyProfileCreateCompanyProfileMeData = {
    body: CompanyProfileCreate;
    path?: never;
    query?: never;
    url: '/api/v1/company-profile/me';
};

export type companyProfileCreateCompanyProfileMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type companyProfileCreateCompanyProfileMeError = companyProfileCreateCompanyProfileMeErrors[keyof companyProfileCreateCompanyProfileMeErrors];

export type companyProfileCreateCompanyProfileMeResponses = {
    /**
     * Successful Response
     */
    200: CompanyProfilePublic;
};

export type companyProfileCreateCompanyProfileMeResponse = companyProfileCreateCompanyProfileMeResponses[keyof companyProfileCreateCompanyProfileMeResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];

export type toolsLoadSourceData = {
    body: LoadRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/rag/load';
};

export type toolsLoadSourceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsLoadSourceError = toolsLoadSourceErrors[keyof toolsLoadSourceErrors];

export type toolsLoadSourceResponses = {
    /**
     * Response Tools-Load Source
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsLoadSourceResponse = toolsLoadSourceResponses[keyof toolsLoadSourceResponses];

export type toolsChunkTextData = {
    body: ChunkRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/rag/chunk';
};

export type toolsChunkTextErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsChunkTextError = toolsChunkTextErrors[keyof toolsChunkTextErrors];

export type toolsChunkTextResponses = {
    /**
     * Response Tools-Chunk Text
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsChunkTextResponse = toolsChunkTextResponses[keyof toolsChunkTextResponses];

export type toolsIngestSourceData = {
    body: IngestRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/rag/ingest';
};

export type toolsIngestSourceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsIngestSourceError = toolsIngestSourceErrors[keyof toolsIngestSourceErrors];

export type toolsIngestSourceResponses = {
    /**
     * Response Tools-Ingest Source
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsIngestSourceResponse = toolsIngestSourceResponses[keyof toolsIngestSourceResponses];

export type toolsCompleteData = {
    body: CompleteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/llm/complete';
};

export type toolsCompleteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsCompleteError = toolsCompleteErrors[keyof toolsCompleteErrors];

export type toolsCompleteResponses = {
    /**
     * Response Tools-Complete
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type toolsCompleteResponse = toolsCompleteResponses[keyof toolsCompleteResponses];

export type toolsGenerateData = {
    body: GenerateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/rag/generate';
};

export type toolsGenerateErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsGenerateError = toolsGenerateErrors[keyof toolsGenerateErrors];

export type toolsGenerateResponses = {
    /**
     * Response Tools-Generate
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsGenerateResponse = toolsGenerateResponses[keyof toolsGenerateResponses];

export type toolsCrawlWebsiteData = {
    body: CrawlWebsiteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/firecrawl/crawl';
};

export type toolsCrawlWebsiteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsCrawlWebsiteError = toolsCrawlWebsiteErrors[keyof toolsCrawlWebsiteErrors];

export type toolsCrawlWebsiteResponses = {
    /**
     * Response Tools-Crawl Website
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsCrawlWebsiteResponse = toolsCrawlWebsiteResponses[keyof toolsCrawlWebsiteResponses];

export type toolsScrapeWebsiteData = {
    body: ScrapeWebsiteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/firecrawl/scrape';
};

export type toolsScrapeWebsiteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsScrapeWebsiteError = toolsScrapeWebsiteErrors[keyof toolsScrapeWebsiteErrors];

export type toolsScrapeWebsiteResponses = {
    /**
     * Response Tools-Scrape Website
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsScrapeWebsiteResponse = toolsScrapeWebsiteResponses[keyof toolsScrapeWebsiteResponses];

export type toolsSearchData = {
    body: SearchRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/firecrawl/search';
};

export type toolsSearchErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsSearchError = toolsSearchErrors[keyof toolsSearchErrors];

export type toolsSearchResponses = {
    /**
     * Response Tools-Search
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsSearchResponse = toolsSearchResponses[keyof toolsSearchResponses];

export type toolsExtractData = {
    body: ExtractRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tools/firecrawl/extract';
};

export type toolsExtractErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type toolsExtractError = toolsExtractErrors[keyof toolsExtractErrors];

export type toolsExtractResponses = {
    /**
     * Response Tools-Extract
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type toolsExtractResponse = toolsExtractResponses[keyof toolsExtractResponses];
