"""add self_description to company profile

Revision ID: 0a48480086fa
Revises: b35354525a43
Create Date: 2026-09-17 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '0a48480086fa'
down_revision = 'b35354525a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companyprofile', sa.Column('self_description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companyprofile', 'self_description')
    # ### end Alembic commands ###
