"""add bidpin and dashboardrefreshstate tables for the bids dashboard

Revision ID: 5415d6a26e9a
Revises: ae2c15270845
Create Date: 2026-09-18 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '5415d6a26e9a'
down_revision = 'ae2c15270845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'dashboardrefreshstate',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('new_since_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_new_count', sa.Integer(), nullable=False),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'bidpin',
        sa.Column('contract_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('contract_id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bidpin')
    op.drop_table('dashboardrefreshstate')
    # ### end Alembic commands ###
