"""Add Company, Filing, FinancialFact tables

Revision ID: 5c92af3ae158
Revises: fe56fa70289e
Create Date: 2026-09-08 15:28:02.231412

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5c92af3ae158'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('sic_code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_cik'), 'company', ['cik'], unique=True)
    op.create_table('filing',
    sa.Column('accession_number', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('form_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('period_of_report', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('previous_filing_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_filing_id'], ['filing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filing_accession_number'), 'filing', ['accession_number'], unique=True)
    op.create_index(op.f('ix_filing_company_id'), 'filing', ['company_id'], unique=False)
    op.create_table('financialfact',
    sa.Column('taxonomy', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('concept', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filing_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financialfact_concept'), 'financialfact', ['concept'], unique=False)
    op.create_index(op.f('ix_financialfact_filing_id'), 'financialfact', ['filing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financialfact_filing_id'), table_name='financialfact')
    op.drop_index(op.f('ix_financialfact_concept'), table_name='financialfact')
    op.drop_table('financialfact')
    op.drop_index(op.f('ix_filing_company_id'), table_name='filing')
    op.drop_index(op.f('ix_filing_accession_number'), table_name='filing')
    op.drop_table('filing')
    op.drop_index(op.f('ix_company_cik'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
