"""add contract table with document contents and duplicate tracking

Revision ID: 83bd4ee543b3
Revises: 1b78c53532bc
Create Date: 2026-09-18 02:55:46.432121

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '83bd4ee543b3'
down_revision = '1b78c53532bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
