"""add contract table with document contents and duplicate tracking

Revision ID: ae2c15270845
Revises: 83bd4ee543b3
Create Date: 2026-09-18 03:12:57.172629

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ae2c15270845'
down_revision = '83bd4ee543b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
