"""add company profile table

Revision ID: b35354525a43
Revises: fe56fa70289e
Create Date: 2026-09-17 17:24:14.696266

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b35354525a43'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companyprofile',
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('base_location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('annual_revenue_eur', sa.Float(), nullable=True),
    sa.Column('max_radius_km', sa.Integer(), nullable=True),
    sa.Column('min_contract_value_eur', sa.Float(), nullable=True),
    sa.Column('max_contract_value_eur', sa.Float(), nullable=True),
    sa.Column('partner_threshold_eur', sa.Float(), nullable=True),
    sa.Column('served_regions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('excluded_regions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('capabilities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('explicit_exclusions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('certifications', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('contractor_role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('max_self_perform_pct', sa.Integer(), nullable=True),
    sa.Column('guarantee_limit_total_eur', sa.Float(), nullable=True),
    sa.Column('guarantee_currently_committed_eur', sa.Float(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('capacity_note', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('reference_projects', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('custom_hardliners', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companyprofile')
    # ### end Alembic commands ###
