"""simplify company profile to free-text sections

Revision ID: c5dcd9194f63
Revises: 0a48480086fa
Create Date: 2026-09-18 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5dcd9194f63'
down_revision = '0a48480086fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companyprofile', 'max_radius_km')
    op.drop_column('companyprofile', 'served_regions')
    op.drop_column('companyprofile', 'excluded_regions')
    op.drop_column('companyprofile', 'min_contract_value_eur')
    op.drop_column('companyprofile', 'max_contract_value_eur')
    op.drop_column('companyprofile', 'partner_threshold_eur')
    op.drop_column('companyprofile', 'explicit_exclusions')
    op.drop_column('companyprofile', 'max_self_perform_pct')
    op.drop_column('companyprofile', 'guarantee_limit_total_eur')
    op.drop_column('companyprofile', 'guarantee_currently_committed_eur')
    op.drop_column('companyprofile', 'available_from')
    op.drop_column('companyprofile', 'capacity_note')
    op.drop_column('companyprofile', 'custom_hardliners')

    # capabilities/certifications/reference_projects keep their names but
    # switch from a Postgres ARRAY to free text.
    op.drop_column('companyprofile', 'capabilities')
    op.drop_column('companyprofile', 'certifications')
    op.drop_column('companyprofile', 'reference_projects')
    op.add_column('companyprofile', sa.Column('capabilities', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('companyprofile', sa.Column('certifications', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('companyprofile', sa.Column('reference_projects', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))

    # contractor_role keeps its name, just gets more room.
    op.alter_column(
        'companyprofile', 'contractor_role',
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=32),
        type_=sqlmodel.sql.sqltypes.AutoString(length=500),
        existing_nullable=True,
    )

    op.add_column('companyprofile', sa.Column('geographic_reach', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('companyprofile', sa.Column('contract_size', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('companyprofile', sa.Column('exclusions', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('companyprofile', sa.Column('capacity', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('companyprofile', sa.Column('hardliners', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companyprofile', 'hardliners')
    op.drop_column('companyprofile', 'capacity')
    op.drop_column('companyprofile', 'exclusions')
    op.drop_column('companyprofile', 'contract_size')
    op.drop_column('companyprofile', 'geographic_reach')

    op.alter_column(
        'companyprofile', 'contractor_role',
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
        type_=sqlmodel.sql.sqltypes.AutoString(length=32),
        existing_nullable=True,
    )

    op.drop_column('companyprofile', 'reference_projects')
    op.drop_column('companyprofile', 'certifications')
    op.drop_column('companyprofile', 'capabilities')
    op.add_column('companyprofile', sa.Column('reference_projects', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('companyprofile', sa.Column('certifications', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('companyprofile', sa.Column('capabilities', postgresql.ARRAY(sa.String()), nullable=True))

    op.add_column('companyprofile', sa.Column('custom_hardliners', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('companyprofile', sa.Column('capacity_note', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('companyprofile', sa.Column('available_from', sa.Date(), nullable=True))
    op.add_column('companyprofile', sa.Column('guarantee_currently_committed_eur', sa.Float(), nullable=True))
    op.add_column('companyprofile', sa.Column('guarantee_limit_total_eur', sa.Float(), nullable=True))
    op.add_column('companyprofile', sa.Column('max_self_perform_pct', sa.Integer(), nullable=True))
    op.add_column('companyprofile', sa.Column('explicit_exclusions', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('companyprofile', sa.Column('partner_threshold_eur', sa.Float(), nullable=True))
    op.add_column('companyprofile', sa.Column('max_contract_value_eur', sa.Float(), nullable=True))
    op.add_column('companyprofile', sa.Column('min_contract_value_eur', sa.Float(), nullable=True))
    op.add_column('companyprofile', sa.Column('excluded_regions', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('companyprofile', sa.Column('served_regions', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('companyprofile', sa.Column('max_radius_km', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
