"""add contract table

Revision ID: cc9879555371
Revises: ae2c15270845
Create Date: 2026-09-18 10:10:43.865481

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cc9879555371'
down_revision = 'ae2c15270845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notice_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notice_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lot_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publication_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('buyer_names', sa.JSON(), nullable=False),
    sa.Column('procedure_title', sa.Text(), nullable=True),
    sa.Column('main_nature', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('main_cpv_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('additional_cpv_codes', sa.JSON(), nullable=False),
    sa.Column('place_of_performance', sa.JSON(), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deadline_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deadline_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('procurement_document_links', sa.JSON(), nullable=False),
    sa.Column('document_contents', sa.JSON(), nullable=False),
    sa.Column('document_contents_text', sa.Text(), nullable=True),
    sa.Column('duplicate_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duplicate_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notice_identifier', 'notice_version', 'lot_identifier', name='uq_contract_notice_version_lot')
    )
    op.create_index(op.f('ix_contract_duplicate_group_id'), 'contract', ['duplicate_group_id'], unique=False)
    op.create_index(op.f('ix_contract_notice_identifier'), 'contract', ['notice_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_notice_identifier'), table_name='contract')
    op.drop_index(op.f('ix_contract_duplicate_group_id'), table_name='contract')
    op.drop_table('contract')
    # ### end Alembic commands ###
