"""Add Filing.primary_document and NarrativeChange table

Revision ID: e46f87fc9cd2
Revises: 5c92af3ae158
Create Date: 2026-09-10 12:28:41.368639

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e46f87fc9cd2'
down_revision = '5c92af3ae158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narrativechange',
    sa.Column('section_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('change_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('new_excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('old_excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filing_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrativechange_filing_id'), 'narrativechange', ['filing_id'], unique=False)
    op.add_column('filing', sa.Column('primary_document', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filing', 'primary_document')
    op.drop_index(op.f('ix_narrativechange_filing_id'), table_name='narrativechange')
    op.drop_table('narrativechange')
    # ### end Alembic commands ###
