// Hand-written client for the new `/api/v1/bids` endpoints
// (backend/app/api/routes/bids.py).
//
// The rest of this app's API client (src/client/**) is generated by
// `npm run generate-client` (@hey-api/openapi-ts) from the backend's live
// OpenAPI schema, and that command overwrites everything under src/client
// on every run. This file lives outside that directory on purpose so it
// survives a regeneration; once the backend is deployed and the client is
// regenerated, the `bids` tag will show up in src/client too and this file
// can be dropped in favor of the generated `BidsService`.
//
// It reuses the same configured axios client (base URL + bearer auth
// already wired up in src/main.tsx) and follows the exact calling
// convention @hey-api/openapi-ts itself generates, so it behaves the same
// as every other service in this app (e.g. `response.data`, throwing on
// non-2xx by default).

import type { Options } from "@/client"
import { client } from "@/client/client.gen"

const BASE_URL = "/api/v1/bids"

export type BidSourceFilter = "all" | "ted" | "oeffentlichevergabe"

export interface BidPublic {
  id: string
  source_system: string
  buyer: string | null
  link: string | null
  estimated_value: number | null
  currency: string | null
  deadline_date: string | null
  deadline_time: string | null
  procedure_title: string | null
  publication_date: string | null
  pinned: boolean
  is_new: boolean
}

export interface BidsPublic {
  data: BidPublic[]
  count: number
}

export type RefreshStatus = "idle" | "running" | "error"

export interface RefreshStatusPublic {
  status: RefreshStatus
  last_refreshed_at: string | null
  new_count: number
  message: string
  error: string | null
}

export interface BidsMessage {
  message: string
}

// `url` is required by @hey-api's `TDataShape`/`Options` constraint (it's
// stripped back out of the actual call options by `Options<TData>` --  the
// real URL is the literal passed to `client.get/post/delete` below), so
// every data shape declares it as a literal, matching how the generated
// `itemsReadItemsData`-style types in src/client/types.gen.ts do it.
interface ReadBidsData {
  query?: { source?: BidSourceFilter }
  url: "/api/v1/bids/"
}

interface BidIdData {
  path: { id: string }
  url: "/api/v1/bids/{id}/pin"
}

interface RefreshData {
  url: "/api/v1/bids/refresh"
}

interface RefreshStatusData {
  url: "/api/v1/bids/refresh/status"
}

// A plain object of functions (not a class) -- same call-site ergonomics as
// the generated `XyzService` objects (`BidsService.readBids(...)`) without
// a static-only class.
export const BidsService = {
  readBids<ThrowOnError extends boolean = true>(
    options?: Options<ReadBidsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<BidsPublic, unknown, ThrowOnError>({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: `${BASE_URL}/`,
      ...options,
    })
  },

  pinBid<ThrowOnError extends boolean = true>(
    options: Options<BidIdData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<BidsMessage, unknown, ThrowOnError>({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: `${BASE_URL}/{id}/pin`,
      ...options,
    })
  },

  unpinBid<ThrowOnError extends boolean = true>(
    options: Options<BidIdData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      BidsMessage,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: `${BASE_URL}/{id}/pin`,
      ...options,
    })
  },

  refresh<ThrowOnError extends boolean = true>(
    options?: Options<RefreshData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      RefreshStatusPublic,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: `${BASE_URL}/refresh`,
      ...options,
    })
  },

  refreshStatus<ThrowOnError extends boolean = true>(
    options?: Options<RefreshStatusData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      RefreshStatusPublic,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: `${BASE_URL}/refresh/status`,
      ...options,
    })
  },
}
