// Hand-written client for the new `/api/v1/profiles` endpoints
// (backend/app/api/routes/profiles.py), which back the "Profiles" tab
// (formerly "Items").
//
// The rest of this app's API client (src/client/**) is generated by
// `npm run generate-client` (@hey-api/openapi-ts) from the backend's live
// OpenAPI schema, and that command overwrites everything under src/client
// on every run. This file lives outside that directory on purpose so it
// survives a regeneration; once the backend is deployed and the client is
// regenerated, the `profiles` tag will show up in src/client too and this
// file can be dropped in favor of the generated `ProfilesService`. See
// src/lib/bidsApi.ts for the same pattern used first.
//
// It reuses the same configured axios client (base URL + bearer auth
// already wired up in src/main.tsx) and follows the exact calling
// convention @hey-api/openapi-ts itself generates, so it behaves the same
// as every other service in this app (e.g. `response.data`, throwing on
// non-2xx by default).

import type { Options } from "@/client"
import { client } from "@/client/client.gen"

const BASE_URL = "/api/v1/profiles"

// Every field is optional -- a contractor can fill this in incrementally,
// and nothing here is required to save a profile.
export interface ProfileFields {
  company_name?: string | null
  base_location?: string | null
  founded_year?: number | null
  employee_count?: number | null
  annual_revenue_eur?: number | null
  geographic_reach?: string | null
  contract_size?: string | null
  capabilities?: string | null
  exclusions?: string | null
  certifications?: string | null
  contractor_role?: string | null
  capacity?: string | null
  reference_projects?: string | null
  hardliners?: string | null
  self_description?: string | null
}

export interface ProfilePublic extends ProfileFields {
  id: string
  owner_id: string
  created_at: string | null
}

export interface ProfilesPublic {
  data: ProfilePublic[]
  count: number
}

export type ProfileCreate = ProfileFields
export type ProfileUpdate = ProfileFields

export interface ProfilesMessage {
  message: string
}

// `url` is required by @hey-api's `TDataShape`/`Options` constraint (see
// the identical note in bidsApi.ts).
interface ReadProfilesData {
  query?: { skip?: number; limit?: number }
  url: "/api/v1/profiles/"
}

interface CreateProfileData {
  body: ProfileCreate
  url: "/api/v1/profiles/"
}

interface ProfileIdData {
  path: { id: string }
  url: "/api/v1/profiles/{id}"
}

interface UpdateProfileData {
  path: { id: string }
  body: ProfileUpdate
  url: "/api/v1/profiles/{id}"
}

// A plain object of functions (not a class) -- same call-site ergonomics as
// the generated `XyzService` objects (`ProfilesService.readProfiles(...)`)
// without a static-only class.
export const ProfilesService = {
  readProfiles<ThrowOnError extends boolean = true>(
    options?: Options<ReadProfilesData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      ProfilesPublic,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: `${BASE_URL}/`,
      ...options,
    })
  },

  createProfile<ThrowOnError extends boolean = true>(
    options: Options<CreateProfileData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      ProfilePublic,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: `${BASE_URL}/`,
      ...options,
    })
  },

  updateProfile<ThrowOnError extends boolean = true>(
    options: Options<UpdateProfileData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<ProfilePublic, unknown, ThrowOnError>(
      {
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: `${BASE_URL}/{id}`,
        ...options,
      },
    )
  },

  deleteProfile<ThrowOnError extends boolean = true>(
    options: Options<ProfileIdData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      ProfilesMessage,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: `${BASE_URL}/{id}`,
      ...options,
    })
  },
}
